export default {
  title: 'Mastering Grunge with the Best Covers',
  bands: [
    {
      title: 'Foo Fighters',
      slug: 'foo-fighters',
      number: 1,
      image: 'foo-fighters',
      songs: [
        {
          title: 'The Pretender',
          slug: 'the-pretender',
          number: 1,
          videoId: 'DPwTJ_s2jLU?si=IMfQ1XIyFaP13237',
          text: `This is the text for the cover of the song The Pretender`,
          image: 'the-pretender.jpeg',
        },
        {
          title: 'My Hero',
          slug: 'my-hero',
          number: 2,
          videoId: 'seK_Uay8Z80?si=E3PPWq-SkR_GUd3T',
          text: `This is the text for the cover of the song My Hero.`,
          image: 'my-hero.jpeg',
        },
        {
          title: 'Best of You',
          slug: 'best-of-you',
          number: 3,
          videoId: '8DFp2rxsvb0?si=EuJahJXgrvP6yjCn',
          text: `This is the text for the cover of the song Best of You.`,
          image: 'best-of-you.jpeg',
        },
      ],
    },
    {
      title: 'Nirvana',
      slug: 'nirvana',
      number: 2,
      image: 'nirvana',
      songs: [
        {
          title: 'Breed',
          slug: 'breed',
          number: 1,
          videoId: '2bYfU_4xcuI?si=Q9vnZUcDE4t1JoQ2',
          text: `This is the text for the cover of the song Breed.`,
          image: 'breed.jpeg',
        },
        {
          title: 'Territorial Pissings',
          slug: 'territorial-pissings',
          number: 2,
          videoId: 'TTzY9Y6EPj8?si=tgfj9nSOR1AlMEde',
          text: `This is the text for the cover of the song Territorial Pissings.`,
          image: 'territorial-pissings.jpeg',
        },
        {
          title: 'Smells Like Teen Spirit',
          slug: 'smells-like-teen-spirit',
          number: 3,
          videoId: 'jCVo36BWKUo?si=pxH9bviuPf5Q4se1',
          text: `This is the text for the cover of the song Smells Like Teen Spirit.`,
          image: 'smells-like-teen-spirit.jpeg',
        },
        {
          title: 'Come As You Are',
          slug: 'come-as-you-are',
          number: 4,
          videoId: 'vdNrvyke7kM?si=64MDegUV-Tc74r9D',
          text: `This is the text for the cover of the song Come As You Are.`,
          image: 'come-as-you-are.jpeg',
        },
      ],
    },
    {
      title: 'Stone Temple Pilots',
      slug: 'stone-temple-pilots',
      number: 3,
      image: 'stone-temple-pilots',
      songs: [
        {
          title: 'Interstate Love Song',
          slug: 'interstate-love-song',
          number: 1,
          videoId: '2Tg-qhcfsWE?si=a6amNF0m6TzwT7MX',
          text: `This is the text for the cover of the song Interstate Love.`,
          image: 'interstate-love-song.jpeg',
        },
        {
          title: 'Vasoline',
          slug: 'vasoline',
          number: 2,
          videoId: 'DwyETnxtxEE?si=FZjMEtRv-YApMLA5',
          text: `This is the text for the cover of the song Vasoline.`,
          image: 'vasoline.jpeg',
        },
        {
          title: 'Sex Type Thing',
          slug: 'sex-type-thing',
          number: 3,
          videoId: 'j6YgnO9VYxI?si=7eLoO3sk7O1mRMYm',
          text: `This is the text for the cover of the song Sex Type Thing.`,
          image: 'sex-type-thing.jpeg',
        },
        {
          title: 'Trippin on a Hole in a Paper Hear',
          slug: 'trippin-on-a-hole-in-a-paper-hear',
          number: 4,
          videoId: 'vJBUnJhOAMc?si=UPaxaJkvyIpjcqxK',
          text: `This is the text for the cover of the song Trippin on a Hole in a Paper Hear.`,
          image: 'tripping.jpeg',
        },
      ],
    },
    {
      title: 'Foo Fighters',
      slug: 'foo-fighters',
      number: 1,
      image: 'foo-fighters',
      songs: [
        {
          title: 'The Pretender',
          slug: 'the-pretender',
          number: 1,
          videoId: 'DPwTJ_s2jLU?si=IMfQ1XIyFaP13237',
          text: `This is the text for the cover of the song The Pretender`,
          image: 'the-pretender.jpeg',
        },
        {
          title: 'My Hero',
          slug: 'my-hero',
          number: 2,
          videoId: 'seK_Uay8Z80?si=E3PPWq-SkR_GUd3T',
          text: `This is the text for the cover of the song My Hero.`,
          image: 'my-hero.jpeg',
        },
        {
          title: 'Best of You',
          slug: 'best-of-you',
          number: 3,
          videoId: '8DFp2rxsvb0?si=EuJahJXgrvP6yjCn',
          text: `This is the text for the cover of the song Best of You.`,
          image: 'best-of-you.jpeg',
        },
      ],
    },
    {
      title: 'Nirvana',
      slug: 'nirvana',
      number: 2,
      image: 'nirvana',
      songs: [
        {
          title: 'Breed',
          slug: 'breed',
          number: 1,
          videoId: '2bYfU_4xcuI?si=Q9vnZUcDE4t1JoQ2',
          text: `This is the text for the cover of the song Breed.`,
          image: 'breed.jpeg',
        },
        {
          title: 'Territorial Pissings',
          slug: 'territorial-pissings',
          number: 2,
          videoId: 'TTzY9Y6EPj8?si=tgfj9nSOR1AlMEde',
          text: `This is the text for the cover of the song Territorial Pissings.`,
          image: 'territorial-pissings.jpeg',
        },
        {
          title: 'Smells Like Teen Spirit',
          slug: 'smells-like-teen-spirit',
          number: 3,
          videoId: 'jCVo36BWKUo?si=pxH9bviuPf5Q4se1',
          text: `This is the text for the cover of the song Smells Like Teen Spirit.`,
          image: 'smells-like-teen-spirit.jpeg',
        },
        {
          title: 'Come As You Are',
          slug: 'come-as-you-are',
          number: 4,
          videoId: 'vdNrvyke7kM?si=64MDegUV-Tc74r9D',
          text: `This is the text for the cover of the song Come As You Are.`,
          image: 'come-as-you-are.jpeg',
        },
      ],
    },
    {
      title: 'Stone Temple Pilots',
      slug: 'stone-temple-pilots',
      number: 3,
      image: 'stone-temple-pilots',
      songs: [
        {
          title: 'Interstate Love Song',
          slug: 'interstate-love-song',
          number: 1,
          videoId: '2Tg-qhcfsWE?si=a6amNF0m6TzwT7MX',
          text: `This is the text for the cover of the song Interstate Love.`,
          image: 'interstate-love-song.jpeg',
        },
        {
          title: 'Vasoline',
          slug: 'vasoline',
          number: 2,
          videoId: 'DwyETnxtxEE?si=FZjMEtRv-YApMLA5',
          text: `This is the text for the cover of the song Vasoline.`,
          image: 'vasoline.jpeg',
        },
        {
          title: 'Sex Type Thing',
          slug: 'sex-type-thing',
          number: 3,
          videoId: 'j6YgnO9VYxI?si=7eLoO3sk7O1mRMYm',
          text: `This is the text for the cover of the song Sex Type Thing.`,
          image: 'sex-type-thing.jpeg',
        },
        {
          title: 'Trippin on a Hole in a Paper Hear',
          slug: 'trippin-on-a-hole-in-a-paper-hear',
          number: 4,
          videoId: 'vJBUnJhOAMc?si=UPaxaJkvyIpjcqxK',
          text: `This is the text for the cover of the song Trippin on a Hole in a Paper Hear.`,
          image: 'tripping.jpeg',
        },
      ],
    },
  ],
};
